// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config'
import { defineConfig, env } from 'prisma/config'

export default defineConfig({
  schema: './src/services/database/prisma/schema/schema.prisma',
  migrations: {
    path: './src/services/database/prisma/migrations',
  },
  datasource: {
    url: env('PRISMA_DB_SQLITE_FILE'),
  },
})
